# Generated by Django 5.2 on 2025-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavraWarao', models.CharField(max_length=255, unique=True)),
                ('palavraPortugues', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
