# Generated by Django 5.2 on 2025-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavras', '0002_palavra_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='palavraWarao',
            field=models.CharField(max_length=255),
        ),
    ]
